mvcMusic/Models/Song.cs
using System;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace MvcMusic.Models
{
    public class Song
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Singer { get; set; }

        [Display(Name = "Release Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:d}", ApplyFormatInEditMode = true)]
        public DateTime ReleaseDate { get; set; }
        public int GenreID { get; set; }
        public Genre Genre { get; set; }
    }
    public class MusicDBContext : DbContext
    {
        public DbSet<Song> Songs { get; set; }
        public DbSet<Genre> Genres { get; set; }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Song>()
                .HasRequired<Genre>(s => s.Genre)
                .WithMany(g => g.Songs)
                .HasForeignKey<int>(s => s.GenreID);
        }
    }
}

mvcMusic/Controllers/SongsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MvcMusic.Models;
using MvcMusic.Models.ViewModels;
using MvcMusic.Repositories;

namespace MvcMusic.Controllers
{
    public class SongsController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();


        // GET: Songs
        public ActionResult Index(string Genre, string Song, string Singer)
        {
            var GenreLst = new List<string>();

            var GenreQry = from d in unitOfWork.GenreRepository.Get()
                          orderby d.Name
                         select d.Name;

            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.Genre = new SelectList(GenreLst);

            var songs = from m in unitOfWork.SongRepository.Get()
                         select m;

            if (!String.IsNullOrEmpty(Song))
            {
                songs = songs.Where(s => s.Title.IndexOf(Song, StringComparison.OrdinalIgnoreCase) >= 0);
            }

            if (!String.IsNullOrEmpty(Singer))
            {
                songs = songs.Where(z => z.Singer.IndexOf(Singer, StringComparison.OrdinalIgnoreCase) >=0);
            }

            if (!string.IsNullOrEmpty(Genre))
            {
                songs = songs.Where(x => x.Genre.Name == Genre);
            }
            var model = new List<SongVM>();
            foreach(var s in songs)
            {
                var genre = unitOfWork.GenreRepository.GetByID(s.GenreID);
                var songToAdd = new SongVM
                {
                    ID = s.ID,
                    GenreName = genre.Name,
                    ReleaseDate = s.ReleaseDate,
                    Singer = s.Singer,
                    Title = s.Title
                };
                model.Add(songToAdd);
            }
            return View(model);
        }

        // GET: Songs/Details/5
        public ViewResult Details(int id)
        {
            Song song = unitOfWork.SongRepository.GetByID(id);
            var genre = unitOfWork.GenreRepository.GetByID(song.GenreID);
            var model = new SongDetailsVM
            {
                ID = song.ID,
                ReleaseDate = song.ReleaseDate,
                Singer = song.Singer,
                Title = song.Title,
                GenreName = genre.Name
            };
            return View(model);
        }

            // GET: Songs/Create
        public ActionResult Create()
        {
            var model = new SongCreateVM();
            var genres = unitOfWork.GenreRepository.Get();
            foreach(var g in genres)
            {
                var genre = new SelectListItem
                {
                    Text = g.Name,
                    Value = g.ID.ToString()
                };
                model.Genres.Add(genre);
            }
            return View(model);
        }

        // POST: Songs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title,Singer,ReleaseDate,GenreID,Genres")] SongCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var genre = unitOfWork.GenreRepository.GetByID(model.GenreID);
                if (genre == null) return View(model);
                var song = new Song
                {
                    Title = model.Title,
                    ReleaseDate = model.ReleaseDate,
                    Singer = model.Singer,
                    Genre = genre
                };
                unitOfWork.SongRepository.Insert(song);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }

            return View(model);
        }

        // GET: Songs/Edit/5
        public ActionResult Edit(int id)
        {
            Song song = unitOfWork.SongRepository.GetByID(id);
            if (song == null) return RedirectToAction("Index");
            var model = new SongEditVM
            {
                ID = song.ID,
                Title = song.Title,
                Singer = song.Singer,
                ReleaseDate = song.ReleaseDate
            };
            var genres = unitOfWork.GenreRepository.Get();
            foreach (var g in genres)
            {
                var genre = new SelectListItem
                {
                    Text = g.Name,
                    Value = g.ID.ToString(),
                    Selected = g.ID == song.GenreID
                };
                model.Genres.Add(genre);
            }
            return View(model);
        }

        // POST: Songs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Title,Singer,ReleaseDate,GenreID,Genres")] SongEditVM model)
        {
            if (ModelState.IsValid)
            {
                var genre = unitOfWork.GenreRepository.GetByID(model.GenreID);
                if (genre == null) return View(model);
                var song = new Song
                {
                    ID = model.ID,
                    Title = model.Title,
                    ReleaseDate = model.ReleaseDate,
                    Singer = model.Singer,
                    Genre = genre,
                    GenreID = genre.ID
                };
                unitOfWork.SongRepository.Update(song);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET: Songs/Delete/5
        public ActionResult Delete(int id)
        {
            Song song = unitOfWork.SongRepository.GetByID(id);
            var genre = unitOfWork.GenreRepository.GetByID(song.GenreID);
            var model = new SongDetailsVM
            {
                ID = song.ID,
                ReleaseDate = song.ReleaseDate,
                Singer = song.Singer,
                Title = song.Title,
                GenreName = genre.Name
            };
            return View(model);
        }

        // POST: Songs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Song song = unitOfWork.SongRepository.GetByID(id);
            unitOfWork.SongRepository.Delete(id);
            unitOfWork.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unitOfWork.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

mvcMusic/Views/Songs/Create.cshtml
@model MvcMusic.Models.ViewModels.SongCreateVM

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Singer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Singer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Singer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.GenreID, Model.Genres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mvcMusic/Views/Songs/Delete.cshtml
@model MvcMusic.Models.ViewModels.SongDetailsVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Song</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Singer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Singer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

mvcMusic/Views/Songs/Details.cshtml
@model MvcMusic.Models.ViewModels.SongDetailsVM

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Song</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Singer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Singer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GenreName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GenreName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

mvcMusic/Views/Songs/Edit.cshtml
@model MvcMusic.Models.ViewModels.SongEditVM

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Song</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Singer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Singer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Singer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.GenreID, Model.Genres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

mvcMusic/Views/Songs/Index.cshtml
@model IEnumerable<MvcMusic.Models.ViewModels.SongVM>

@{
    ViewBag.Title = "Index";
}

<h2>Songs</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @using (Html.BeginForm("Index", "Songs", FormMethod.Get))
    {
    <p>
        Genre: @Html.DropDownList("Genre", "All Genre")
        Title: @Html.TextBox("Song")
        Singer: @Html.TextBox("Singer")
        <input type="submit" value="Search" />
    </p>
}
    
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Singer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GenreName)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Singer)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GenreName)
        </td>
        @if (User.IsInRole("Admin") | User.IsInRole("Moderator"))
        {
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
        @if (User.IsInRole("Admin"))
            { 
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            }
    </td>
        }
    </tr>
        }

    </table>